version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: creditcard_simulator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:localpassword@postgres:5432/creditcard_simulator
      JWT_SECRET: local-development-jwt-secret-key-min-32-chars
      CORS_ORIGIN: http://localhost:8080
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:3001
    environment:
      NODE_ENV: production
      VITE_API_BASE_URL: http://localhost:3001
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
